services:
  - type: web
    name: zaxxy-downloader
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python main.py
    plan: free